services:
  - type: web
    name: notifyhub
    env: docker
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn NotifyHub.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_TOKEN_LIFETIME_MINUTES
        value: "60"
      - key: REFRESH_TOKEN_LIFETIME_MINUTES
        value: "1440"
