services:
  - type: web
    name: NotifyHub-web
    runtime: docker
    plan: starter
    region: oregon
    buildCommand: docker build -t notifyhub .
    startCommand: |
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:$PORT NotifyHub.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: NotifyHub-web
          property: host
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: NotifyHub-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: NotifyHub.settings
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true

  - type: pserv
    name: NotifyHub-db
    runtime: postgresql
    plan: starter
    region: oregon
