# Generated by Django 5.2.4 on 2025-07-22 15:56

from django.db import migrations


def create_notification_types(apps, schema_editor):
    """
    Default NotificationType entries required for event handling.

    The system-defined notification types that correspond to the supported events:
    - New comment posted
    - New login from unrecognized device
    - Weekly summary report

    This data migration ensures these values exist in every environment after migration.
    """
    NotificationType = apps.get_model("notification", "NotificationType")

    NotificationType.objects.get_or_create(
        notification_code="new_comment", defaults={"name": "New Comment"}
    )
    NotificationType.objects.get_or_create(
        notification_code="new_login", defaults={"name": "New Login"}
    )
    NotificationType.objects.get_or_create(
        notification_code="weekly_summary", defaults={"name": "Weekly Summary"}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_notification_types, reverse_code=migrations.RunPython.noop
        ),
    ]
