# Generated by Django 5.2.4 on 2025-08-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="The location of the user, e.g., city or country.",
                max_length=255,
                null=True,
                verbose_name="location",
            ),
        ),
    ]
